### PR TITLE
Regex match: allow partially entered portions of names

### PR DESCRIPTION
**Pull request by gauteh**
Allow partially entered names to be matched

### CODE REVIEW

**Comment by adborden** [comment]
Howdy, thanks for the pull request! I didn't even realize this was a bug. Is it possible to fix it without regular expressions? I think that using regular expressions in autocomplete is a bit un-natrual.

**Comment by gauteh** [comment]
Aaron D Borden writes on juni 10, 2017 20:44:
> Howdy, thanks for the pull request! I didn't even realize this was a bug. Is it possible to fix it without regular expressions? I think that using regular expressions in autocomplete is a bit un-natrual.

Don't think so if we want it to be case-insensitive. You don't need to
enter regexp in the To: field, the regexp is added by the plugin.
Anyway, it might still cause confusion since escaping is only
rudimentary.

**Comment by adborden** [comment]
How does this work for you? https://github.com/adborden/vim-notmuch-address/compare/bug/partial-match

**Comment by gauteh** [comment]
Aaron D Borden writes on juni 10, 2017 21:41:
> How does this work for you? https://github.com/adborden/vim-notmuch-address/compare/bug/partial-match
> 

Hi, I think this works - but I'm not sure why :) I seem to remember I had 
problems with case sensitivity before.

**Comment by gauteh** [comment]
Hi @adborden, I think your solution works pretty well - it works better than mine at least.

**Comment by adborden** [comment]
Thanks, I really appreciate you testing it out. I just merged the fix to master.

**Pull request closed without merging**
